src/goods/entities/categories.entity.ts
src/goods/entities/goods.entity.ts
src/goods/entities/stocks.entity.ts

goods/categories/stocks
없음
엔티티 추가

Feat : goods/categories/stocks entity

---

src/goods/entities/categories.entity.ts
src/goods/entities/goods.entity.ts
src/goods/entities/stocks.entity.ts
src/user/entities/user.entitiy.ts

goods/categories/stocks/users
엔티티 class-validator 추가
+ 결제 api를 위해 user 테이블에 points 컬럼 추가(오로지 결제 수단일 뿐임, history 및 구체적인 구현은 2단계에 진행 예정)

엔티티 싱크 맞추기 완료

---

configs/typeOrmModuleOption.ts
src/app.module.ts
src/goods/dto/create-goods.dto.ts
src/goods/dto/update-goods.dto.ts
src/goods/goods.controller.spec.ts
src/goods/goods.controller.ts
src/goods/goods.module.ts
src/goods/goods.service.spec.ts
src/goods/goods.service.ts

goods/categories/stocks
TypeOrmModule.forFeature 추가하였습니다.

Feat : goods 모듈 등록

---

src/goods/entities/goods.entity.ts
src/goods/goods.controller.ts
src/goods/goods.service.ts

Fix : order와의 entity 관계 설정

---

src/goods/entities/goods.entity.ts

Fix : order 임포트..

---

src/app.module.ts

Feat : app.module 통합

---

src/goods/goods.module.ts
src/orders/orders.module.ts

Fix : 관계 추가(import)

---

package-lock.json
package.json
src/goods/goods.controller.ts
src/goods/goods.service.ts

Domain goods

---

src/goods/dto/update-goods.dto.ts
src/goods/goods.controller.ts
src/goods/goods.service.ts

Feat : Goods Update

---

src/goods/categories.controller.ts
src/goods/categories.service.ts
src/goods/dto/create-categories.dto.ts
src/goods/dto/create-goods.dto.ts
src/goods/goods.controller.ts
src/goods/goods.module.ts
src/goods/goods.service.ts

goods/categories
goods에 categories id 저장하도록

Feat : goods에 categories id 저장하도록

---

src/goods/dto/create-stocks.dto.ts
src/goods/dto/update-stocks.dto.ts
src/goods/entities/stocks.entity.ts
src/goods/goods.module.ts
src/goods/goods.service.ts
src/goods/stocks.controller.ts
src/goods/stocks.service.ts

goods/stocks
StocksService 전체
재고 관리 기능 추가

Feat : 재고 기능 추가

---

src/goods/goods.service.ts

goods/stocks
Feat : 상품 등록시 재고 정보 자동 생성

Feat : 상품 등록시 재고 정보 자동 생성

---

src/goods/entities/goods.entity.ts

	modified:   src/goods/entities/goods.entity.ts

---

src/orders/entities/orders.entity.ts
src/orders/entities/ordersdetails.entity.ts
src/orders/orders.service.ts

오더 오더디테일 엔티티 
ex) 브랜치 생성
오더 오더디테일 엔티티 수정

오더엔티티 관계설정 및 수정

---

src/boards/boards.controller.spec.ts
src/boards/boards.controller.ts
src/boards/boards.module.ts
src/boards/boards.service.spec.ts
src/boards/dto/create-board.dto.ts
src/boards/dto/update-board.dto.ts
src/boards/entities/board.entity.ts

Feat : Board 모듈 생성

---

package-lock.json
src/goods/entities/goods.entity.ts
src/goods/goods.controller.ts
src/main.ts
src/orders/entities/orders.entity.ts
src/orders/entities/ordersdetails.entity.ts
src/orders/orders.service.ts
src/user/entities/user.entitiy.ts

오더 유저 굿즈(오더 원투매니 삭제) 엔티티 수정
ex) 브랜치 생성
굿즈(오더 원투매니 삭제), 굿즈컨트롤러 useguard  불꺼진거 삭제

오더 유저 굿즈 엔티티 수정

---

package-lock.json
src/app.module.ts
src/boards/boards.controller.ts
src/boards/boards.service.ts
src/goods/entities/goods.entity.ts
src/goods/goods.controller.ts

	modified:   src/boards/boards.controller.ts

---

src/goods/goods.module.ts
src/orders/carts.controller.ts
src/orders/carts.service.ts
src/orders/dto/create-cart.dto.ts
src/orders/entities/carts.entity.ts
src/orders/entities/orders.entity.ts
src/orders/orders.service.ts

오더 엔티티 수정. 장바구니 기능 구현(카트 컨트롤러, 서비스, dto)
ex) 브랜치 생성
기능 구현 및 엔티티 수정

장바구니 기능 구현, 오더엔티티 수정

---

src/goods/entities/goods.entity.ts
src/goods/goods.module.ts
src/orders/dto/create-cart.dto.ts

Feat : Carts 엔티티 추가

---

package-lock.json
package.json
src/configs/s3_fileupload.ts
src/goods/dto/create-goods.dto.ts
src/goods/goods.controller.ts
src/goods/goods.module.ts
src/goods/goods.service.ts

Feat : src/configs/s3_fileupload.ts 버킷업로드

---

src/configs/s3_fileupload.ts
src/goods/goods.service.ts

Feat : 파일 삭제

---

src/orders/dto/create-cart.dto.ts
src/orders/dto/create-order.dto.ts
src/orders/orders.controller.ts
src/orders/orders.module.ts
src/orders/orders.service.ts
src/payments/entities/payments.entity.ts
src/payments/payments.controller.ts
src/payments/payments.module.ts
src/payments/payments.service.ts

오더, 페이먼츠
ex) 브랜치 생성
결제 로직 수정, 주문목록 조회 로직 구현, 페이먼츠 엔티티 생성

페이먼트 엔티티 생성 및 주문조회 로직 구현

---

src/payments/payments.service.ts

페이먼트
ex) 브랜치 생성
페이먼트 서비스 포맷 수정

페이먼트서비스 수정

---

src/payments/payments.controller.ts
src/payments/payments.service.ts

페이먼츠
ex) 브랜치 생성
결제 정보 , 목록 조회 기능 구현

결제 정보,결제 목록 조회 기능 구현

---

src/orders/orders.controller.ts
src/payments/entities/payments.entity.ts
src/payments/interfaces/payments.interface.ts
src/payments/payments.controller.ts
src/payments/payments.module.ts
src/payments/payments.service.ts
src/payments/types/payments.type.ts

페이먼츠
ex) 브랜치 생성
결제 취소 기능 구현, 결제 엔티티 수정(결제상태 enum추가), 결제 인터페이스, 타입 추가

결제 취소 기능 구현, 결제 엔티티 수정(결제상태 enum추가), 결제 인터페이스, 타입 추가

---

src/payments/entities/payments.entity.ts

페이먼츠 엔티티
ex) 브랜치 생성
paid 컬럼 삭제

페이먼츠 엔티티 수정

---

.husky/pre-commit
src/goods/categories.controller.spec.ts
src/goods/categories.service.spec.ts
src/goods/goods.controller.spec.ts
src/goods/goods.service.spec.ts
src/goods/stocks.controller.spec.ts
src/goods/stocks.service.spec.ts
src/like/like.service.ts
src/orders/orders.controller.spec.ts
src/orders/orders.service.spec.ts
src/orders/review.controller.spec.ts
src/orders/review.service.spec.ts
src/point/entities/point.entity.ts
src/user/entities/user.entitiy.ts
src/user/user.controller.ts
src/user/users.controller.spec.ts
src/user/users.service.spec.ts

Domain user

---

src/boards/boards.controller.spec.ts
src/boards/boards.controller.ts
src/boards/boards.module.ts
src/boards/boards.service.spec.ts
src/boards/boards.service.ts
src/boards/comments.controller.spec.ts
src/boards/comments.controller.ts
src/boards/comments.service.spec.ts
src/boards/comments.service.ts
src/boards/dto/create-board.dto.ts
src/boards/dto/create-comment.dto.ts
src/boards/dto/update-board.dto.ts
src/boards/dto/update-comment.dto.ts
src/boards/entities/board.entity.ts
src/boards/entities/boards.entity.ts
src/boards/entities/comments.entity.ts
src/configs/validationPipe.ts

boards(+ coments)
boards.controller.spect.ts
boards.service.spec.ts
comments.controller.spec.ts
comments.service.spec.ts
테스트 코드 76 케이스 작성( 68/76)

Domain board

---

src/orders/dto/create-order.dto.ts
src/orders/dto/create-review.dto.ts
src/orders/entities/orders.entity.ts
src/orders/entities/ordersdetails.entity.ts
src/orders/entities/review.entity.ts
src/orders/orders.controller.ts
src/orders/orders.service.ts
src/orders/review.controller.ts
src/orders/review.service.ts
src/payments/payments.controller.ts
src/payments/payments.service.ts

ex) 브랜치 생성
id 값에 0이 들어가는 케이스도 고려해야 할까? -> 0,  null, undefined도 대비하여 수정
ordersdetail - review 엔티티 1:1 연결함
리뷰서비스의 리뷰작성 로직에 트랜잭션 연결 후 배송완료 상태인 경우만 리뷰 작성 가능
리뷰컨트롤러 라우터 오더-> 오더디테일로 변경
purchase 함수랑 카트랑 연결 -> 보류
createOrderDto로도 주문할 수 있고, carts로도 주문할 수 있고 - >보류

오더,리뷰,결제 수정사항 반영

---

src/like/like.service.ts
src/point/entities/point.entity.ts
src/user/dto/update.dto.ts
src/user/entities/user.entitiy.ts
src/user/user.controller.ts
src/user/users.service.ts

금요일 수정사항 완료

---

src/goods/categories.controller.ts
src/goods/goods.controller.ts
src/goods/stocks.controller.ts

	modified:   src/goods/categories.controller.ts

---

potato-task-family-revision3.json

new file:   potato-task-family-revision3.json

---

src/boards/boards.service.ts
src/common/pipe/resize-image.pipe.ts
src/common/utils/s3_fileupload.ts
src/user/users.service.ts

users / boards
s3FileService.uploadFile
파일업로드 경로 지정

modified:   src/boards/boards.service.ts

---

src/like/entities/like.entity.ts
src/point/entities/point.entity.ts
src/user/entities/user.entitiy.ts

ex) user/like/point
user.entity.ts
like.entity.ts
point.entity.ts
ex) 브랜치 생성

user 모듈 point 모듈 like 모듈 절대경로 >> 상대경로 수정

---

src/goods/goods.controller.ts
src/goods/goods.service.ts

modified:   src/goods/goods.controller.ts

---

src/goods/dto/create-goods.dto.ts
src/goods/dto/update-goods.dto.ts

	modified:   src/goods/dto/create-goods.dto.ts

---

src/boards/comments.controller.spec.ts
src/orders/orders.service.spec.ts

orders, comments
orders.service.spec.ts - 트랜잭션 테스트코드 구현 성공
comments.service.spec.ts - 경로 수정

orders service 트랜잭션 테스트 코드 구현 성공

---

src/orders/carts.service.ts
src/orders/dto/create-payment.dto.ts
src/orders/entities/carts.entity.ts
src/orders/entities/orders.entity.ts
src/orders/orders.service.ts
src/payments/entities/payments.entity.ts
src/payments/payments.controller.ts
src/payments/payments.module.ts
src/payments/payments.service.ts

카트, 주문, 결제 수정

---

src/orders/entities/ordersdetails.entity.ts
src/orders/entities/review.entity.ts

오더 디테일,리뷰 엔티티 수정

---

package.json

testing aws cli with OIDC

---

.github/workflows/aws_test.yml

updated github action deploy

---

task_definition.json

	new file:   task_definition.json

---

Dockerfile

modified:   Dockerfile

---

task_definition.json

modified:   task_definition.json

---

package-lock.json
package.json
src/app.module.ts

CDN 테스트 용(캐시 모듈 추가)

---

src/app.module.ts
src/storage/storage.module.ts

new file:   src/storage/storage.module.ts

---

src/app.module.ts
src/redis/redis.module.ts
src/redis/redis.service.spec.ts
src/redis/redis.service.ts

redis-cloud 무료 상품 만료로 인한 일시적 정지

---

src/goods/categories.controller.spec.ts
src/goods/categories.service.spec.ts
src/goods/dto/create-goods.dto.ts
src/goods/dto/create-stocks.dto.ts
src/goods/dto/update-stocks.dto.ts
src/goods/entities/stocks.entity.ts
src/goods/goods.controller.spec.ts
src/goods/goods.controller.ts
src/goods/goods.module.ts
src/goods/goods.service.spec.ts
src/goods/goods.service.ts
src/goods/stocks.controller.spec.ts
src/goods/stocks.service.spec.ts
src/goods/stocks.service.ts
src/storage/dto/create-storage.dto.ts
src/storage/dto/update-storage.dto.ts
src/storage/entities/rack.entity.ts
src/storage/entities/storage.entity.ts
src/storage/storage.controller.spec.ts
src/storage/storage.controller.ts
src/storage/storage.module.ts
src/storage/storage.service.spec.ts
src/storage/storage.service.ts

Feat : 창고 / 창고 Rack

---

src/app.module.ts
src/redis/redis.module.ts
src/redis/redis.service.spec.ts
src/redis/redis.service.ts

redis host 변경(cloud to local)

---

src/goods/dto/create-goods.dto.ts
src/goods/entities/stocks.entity.ts
src/goods/goods.service.ts

Feat : DTO Type 추가

---

src/storage/rack.service.ts

modified:   src/storage/rack.service.ts

---

package-lock.json
package.json

Feat : Elastic Search 모듈

---

src/like/like.module.ts

modified:   src/like/like.module.ts

---

load-test/config.yaml
load-test/test-carts-addToCart.yaml
load-test/test-carts-clearCart.yaml
load-test/test-carts-getCartItems.yaml
load-test/test-carts-removeFromCart.yaml
load-test/test-carts-updateQuantity.yaml
load-test/test-goods-findAll.yaml
load-test/test-goods-findOne.yaml
load-test/test-infos.txt
load-test/test-orders-cancelOrder.yaml
load-test/test-orders-findAllOrderByUser.yaml
load-test/test-orders-findOneOrderByBoth.yaml
load-test/test-orders-purchase.yaml
load-test/test-payments-findAllOrderByUser.yaml
load-test/test-payments-findOneOrderByBoth.yaml
load-test/test-payments-pay.yaml
load-test/test-users-signin.yaml
src/like/like.module.ts
src/orders/orders.service.ts

부하 테스트 모듈 분할

---

src/redis/redis.service.ts

redis module
redis.service.ts: redis client 통합

redis.service.ts: redis client 통합

---

Dockerfile
data-migration/Dockerfile
data-migration/index.js
data-migration/package.json
package-lock.json
package.json
src/app.module.ts
src/elasticsearch/elasticsearch.controller.ts
src/elasticsearch/elasticsearch.module.ts
src/elasticsearch/elasticsearch.service.ts
src/goods/dto/create-stocks.dto.ts
src/goods/entities/goods.entity.ts
src/goods/entities/stocks.entity.ts
src/goods/goods.module.ts
src/goods/goods.service.ts
src/goods/stocks.service.ts
src/storage/rack.service.ts

Feat : Goods/stocks 엔티티 변경

---

package-lock.json
src/orders/orders.service.ts

Fix : orders 오류 수정

---

src/oauth/oauth.module.ts
src/payments/payments.module.ts

Fix :   src/oauth/oauth.module.ts

---

data-migration/index.js
src/elasticsearch/elasticsearch.service.ts
src/goods/entities/goods.entity.ts
src/goods/entities/stocks.entity.ts
src/goods/goods.module.ts
src/goods/goods.service.ts

Feat : 상품검색에 OpenSearch 적용

---

load-test/loadTest-data-carts.ts
load-test/loadTest-data-orders.ts
src/user/user.controller.ts
src/user/users.service.ts

carts 더미 데이터 작성
토큰 갱신 로직 추가
ex) 브랜치 생성

부하 테스트: carts 더미 데이터 작성 // 토큰 갱신 로직 추가

---

src/common/utils/kakao-geocoder.util.ts
src/goods/goods.service.ts
src/goods/stocks.service.ts
src/orders/entities/orders.entity.ts
src/payments/payments.controller.ts
src/payments/payments.module.ts
src/payments/payments.service.ts
src/storage/dto/create-storage.dto.ts
src/storage/entities/rack.entity.ts
src/storage/entities/storage.entity.ts
src/storage/rack.service.ts
src/storage/storage.module.ts
src/storage/storage.service.ts

goods, storage, payments, orders
ex) 브랜치 생성

new file:   src/common/utils/kakao-geocoder.util.ts

---

src/orders/dto/create-order.dto.ts
src/orders/entities/orders.entity.ts
src/orders/orders.service.ts
src/user/entities/user.entitiy.ts
src/user/users.service.ts

Feat : order

---

src/orders/orders.service.ts

orders
orders.service.ts - purchase(좌표를 찾기 위한 주소, 상세주소,  전화번호 추가)
ex) 브랜치 생성

orders 모듈 purchase 메서드 수정

---

src/common/utils/kakao-geocoder.util.ts
src/payments/entities/payments.entity.ts
src/payments/payments.controller.ts
src/payments/payments.module.ts
src/payments/payments.service.ts

payments, kakaogeocoder
payments.service.ts
payments.controller.ts - pay 내부에 구매자 좌표와 가장 가까운 좌표의 창고를 매칭하는 기능 추가
kakaogeocoder.ts - getClosestStore()
ex) 브랜치 생성

카카오 GPS 기반 재고 처리 로직 구현

---

src/payments/entities/tossHistory.entity.ts
src/payments/payments.controller.ts
src/payments/payments.service.ts
src/toss/checkout.html
src/toss/success.html
src/toss/toss.controller.ts

toss
payments
payments.controller.ts - payCash, payCashConfirm
payments.service.ts - payCash, payCashConfirm
토스 페이먼츠 pg 시스템 구축

토스 페이먼츠 pg 시스템 구축

---

src/payments/payments.module.ts
src/payments/payments.service.ts

Fix : 토스 history 의존성 추가

---

client/src/components/PayCashValidationSuccess.vue
src/payments/payments.service.ts
src/storage/entities/rack.entity.ts
src/toss/toss.controller.ts

PayCash.vue
PayCashValidation.vue
toss.controller.ts
toss.service.ts
ex) 브랜치 생성

토스 페이먼츠 연동 완료

---

client/babel.config.js
client/package-lock.json
client/package.json
client/src/assets/css/style.css
client/src/components/CategoryMenu.vue
client/src/components/MainHome.vue
client/src/components/ProductItem.vue
client/src/components/ProductList.vue
client/src/components/SearchBar.vue
client/src/components/ShoppingCart.vue
client/src/components/UserProfileBtn.vue
client/src/main.js
client/src/router/index.js
client/src/store/index.js
client/vue.config.js
data-migration/index.js
src/goods/goods.service.ts

Feat : 프론트

---

src/payments/payments.service.ts

페이먼츠 모듈 오타 수정

---

client/src/components/MainHome.vue
client/src/components/OrderPage.vue
client/src/components/ShoppingCart.vue
client/src/router/index.js

modified:   client/src/components/MainHome.vue

---

client/src/components/PayCashValidationSuccess.vue
package.json

	modified:   client/src/components/PayCashValidationSuccess.vue

---

client/src/components/PayPoint.vue
client/src/router/index.js
src/payments/payments.controller.ts
src/payments/payments.service.ts
src/toss/toss.controller.ts
src/toss/toss.module.ts
src/toss/toss.service.ts

PayPoint 프론트 구축 중

---

package-lock.json
src/main.ts

modified:   src/main.ts

---

package-lock.json
package.json
src/main.ts

Fix : package.json

---

task_definition.json

오픈 서치 환경 변수 추가

---

src/main.ts

	modified:   src/main.ts

---

src/user/user.controller.ts

카카오 로그인 경로 변경

---

client/src/components/OrderShipping.vue
client/src/components/PayCash.vue
client/src/components/PayCashValidation.vue
src/user/user.controller.ts

	modified:   client/src/components/OrderShipping.vue

---

client/src/components/OrderPage.vue
client/src/components/PayCash.vue
client/src/components/PayPoint.vue
client/src/components/UserProfile.vue
src/orders/orders.controller.ts
src/orders/orders.service.ts
src/toss/toss.service.ts

토스 페이먼츠 키 수정 + 주문 정보 조회 시 상품 정보도 팝업 되도록 조정

---

client/src/components/OrderPage.vue
src/payments/payments.controller.ts
src/payments/payments.service.ts
src/toss/toss.controller.ts
src/toss/toss.service.ts

토스 페이먼츠 중복 결제 방지 로직

---

client/src/assets/css/style.css
client/src/components/AdminPage.vue
client/src/components/OrderShipping.vue
client/src/components/PayCashValidationSuccess.vue
client/src/components/ProductItem.vue
client/src/components/UserProfile.vue
client/src/router/index.js

Feat : admin

---

client/src/components/ProductItem.vue
src/user/user.controller.ts
task_definition.json

Feat : 쿠키 설정 수정

---

task_definition.json

	modified:   task_definition.json

---

client/src/components/ProductItem.vue
client/src/components/ShoppingCart.vue
client/src/components/UserProfile.vue
src/orders/carts.service.ts
src/user/user.controller.ts

	modified:   client/src/components/ProductItem.vue

---

src/orders/orders.controller.ts
src/orders/orders.service.ts

modified:   src/orders/orders.controller.ts

---

client/src/components/ProductList.vue
src/elasticsearch/elasticsearch.service.ts
src/goods/goods.service.ts

modified:   src/goods/goods.service.ts

---

client/src/components/StockManagement.vue

modified:   client/src/components/StockManagement.vue

---

client/src/assets/css/style.css
client/src/components/AppFooter.vue
client/src/components/HotDealsBanner.vue
client/src/components/MainHome.vue
client/src/components/OrderManagement.vue
client/src/components/ProductItem.vue
client/src/components/ProductList.vue
client/src/components/UserProfile.vue
client/src/router/index.js
src/orders/orders.controller.ts
src/orders/orders.service.ts

	new file:   client/src/components/HotDealsBanner.vue

---

client/src/assets/css/style.css
client/src/components/OrderManagement.vue
src/orders/orders.service.ts

	modified:   client/src/assets/css/style.css

---

src/user/user.controller.ts

	modified:   src/user/user.controller.ts

---

src/user/user.controller.ts

modified:   src/user/user.controller.ts
